RUN apt-get install -y python3-yaml python3-distutils python3-cryptography json-glib-tools
RUN apt-get install -y python3-requests python3-openssl

# The build system derives a build Dockerfile from this source Dockerfile, and
# appends tarball-injection logic when it does so. Hence this comment!
