# We need some upstream stuff
RUN apt-get install -y python3-yaml python3-distutils python3-cryptography
RUN apt-get install -y file

# The build system derives a build Dockerfile from this source Dockerfile, and
# appends tarball-injection logic when it does so. Hence this comment!
